### ISSUE TITLE
Nav Bar changes

### ISSUE THREAD

**Issue by juliastarkov** [JacobWylie/julia-portfolio#2]
![screen shot 2018-05-27 at 3 32 28 pm](https://user-images.githubusercontent.com/26334275/40626637-bf37d172-626e-11e8-985b-21ff68f0cec2.png)

Two things here: 
- Please remove the "Home" option. This should be linked through the logo.
- Please remove the Active states. The links should be white unless hovered over or clicked. I don't need it to highlight where the user is on the landing page as it's very short, and it doesn't really make sense on other parts of the site. 
- I'm not feeling the bold on this, my bad. If we could please make these all caps and not bold, that would be better.

**Comment by JacobWylie** [comment]
Changed
