### ISSUE TITLE
Contact Layout Updates

### ISSUE THREAD

**Issue by juliastarkov** [JacobWylie/julia-portfolio#6]
![contact specs](https://user-images.githubusercontent.com/26334275/40688688-ea3ff56c-6353-11e8-9487-0ecaf10d7c58.png)

(Added to the Drive as well)

**Comment by juliastarkov** [comment]
![screen shot 2018-05-29 at 3 26 42 pm](https://user-images.githubusercontent.com/26334275/40688891-b4e37d16-6354-11e8-8d76-a4a7615c5d55.png)

As for mobile, you can see here the biggest difference is where the About text starts and the line spacing, which def needs to be wider.

There is also some weird top shadow thing on the email fields? Idk what that's about but can we please remove it? 

As in the desktop version, if we can please add just a bit more white space padding on the sides that would be great. About 15 px on the right and left.

**Comment by juliastarkov** [comment]
(oh also, the email and linkedin icons are bigger here for some reason. Can we make them the same size as the ones in the footer please)

**Comment by JacobWylie** [comment]
Fixed
