### ISSUE TITLE
Work Layout Updates

### ISSUE THREAD

**Issue by juliastarkov** [JacobWylie/julia-portfolio#7]
![featured work specs](https://user-images.githubusercontent.com/26334275/40689626-dccf271e-6357-11e8-86e8-bfd6cbc2671e.png)

Here is how I'm hoping we can lay out the Work boxes. Essentially, I'd like to have the contents auto-center within these parameters. The size of the box and the padding of white space on the sides should be fixed, but besides that the text and image should center horizontally and vertically. Let me know if that makes sense. 

(Also fyi, I noticed that I made a mistake in my earlier mockups with how i centered/laid out the Botanic one, so this is the most up to date version). 

The mobile version looks good. The only thing we'll need to change is the line spacing again. Idk why the default is that tight but whatever!

**Comment by JacobWylie** [comment]
Fixed
