### ISSUE TITLE
Nav Bar Size (Question)

### ISSUE THREAD

**Issue by juliastarkov** [JacobWylie/julia-portfolio#8]
The more I interact with the case study the more annoying the nav bar always being there seems. Is it difficult to have it look slightly different upon scroll? Like, get smaller and have the icon get smaller? 

I wasn't anticipating it being so in the way, and may be other thinking it, so I in no way want to add _more_ work to this. If that's complicated to do don't worry about it. Let me know. 

(this is also lowest priority for me at the moment)

**Comment by JacobWylie** [comment]
Hide navbar on scroll down/show on scroll up
